exports.tmpl = ['',
'/* * * * * * * * * * *',
' Import Fonts',
'* * * * * * * * * * */',
'',
'<% for (var i = 0; i < uie_state.fonts.length; i ++) { var font = uie_state.fonts[i]; %>',
'  @import url("https://fonts.googleapis.com/css?family=<%- font.name %>:400,700,400italic,700italic");',
'<% } %>',
'',
'/* * * * * * * * * * *',
' Base CSS',
'* * * * * * * * * * */',
'',
'<%= uie_state.basecss %>',
'',
'',
'/* * * * * * * * * * *',
' buttons',
'* * * * * * * * * * */',
'',
'<% for (var i = 0; i < uie_state.buttons.length; i ++) { var b = uie_state.buttons[i]; %>',
'',
'.<%= className(b.class_name) %> {',
'<%= b.style %>',
'}',
'',
'<% if (b.hoverStyle) { %>',
'.<%= className(b.class_name) %>:hover {',
'<%= b.hoverStyle %>',
'}',
'<% } %>',
'',
'<% if (b.activeStyle) { %>',
'.<%= className(b.class_name) %>:active {',
'<%= b.activeStyle %>',
'}',
'<% } %>',
'',
'<% } %>',
'',
'/* * * * * * * * * * *',
' Images',
'* * * * * * * * * * */',
'',
'<% for (var i = 0; i <  uie_state.images.length; i ++) { var img =  uie_state.images[i]; %>',
'',
'<%= img.tagName %>.<%= className(img.class_name) %>,',
'div.<%= className(img.class_name) %> {',
'<%= img.style %>',
'}',
'',
'<% } %>',
'',
'/* * * * * * * * * * *',
' Headers',
'* * * * * * * * * * */',
'',
'<% for (var i = 0; i <  uie_state.headerTexts.length; i ++) { var ht =  uie_state.headerTexts[i]; %>',
'',
'<%= ht.tagName %>.<%= className(ht.class_name) %> {',
'<%= ht.style %>',
'}',
'',
'<% } %>',
'',
'/* * * * * * * * * * *',
' Text',
'* * * * * * * * * * */',
'',
'<% for (var i = 0; i <  uie_state.texts.length; i ++) { var t =  uie_state.texts[i]; %>',
'',
'<%= t.tagName %>.<%= className(t.class_name) %> {',
'<%= t.style %>',
'}',
'',
'<% } %>',
'',
'',
'/* * * * * * * * * * *',
' Links',
'* * * * * * * * * * */',
'',
'<% for (var i = 0; i <  uie_state.links.length; i ++) { var l =  uie_state.links[i]; %>',
'',
'<%= l.tagName %>.<%= className(l.class_name) %> {',
'<%= l.style %>',
'}',
'',
'<% if (l.hoverStyle) { %>',
'.<%= className(l.class_name) %>:hover {',
'<%= l.hoverStyle %>',
'}',
'<% } %>',
'',
'<% } %>',
'',
'/* * * * * * * * * * *',
' Text Input',
'* * * * * * * * * * */',
'',
'<% for (var i = 0; i <  uie_state.textInputs.length; i ++) { var ti =  uie_state.textInputs[i]; %>',
'',
'<%= ti.tagName %>.<%= className(ti.class_name) %> {',
'<%= ti.style %>',
'}',
'',
'<% } %>',
'',
'/* * * * * * * * * * *',
' Passwords',
'* * * * * * * * * * */',
'',
'<% for (var i = 0; i <  uie_state.passwords.length; i ++) { var p =  uie_state.passwords[i]; %>',
'',
'<%= p.tagName %>.<%= className(p.class_name) %> {',
'<%= p.style %>',
'}',
'',
'<% } %>',
'',
'/* * * * * * * * * * *',
' Text Areas',
'* * * * * * * * * * */',
'',
'<% for (var i = 0; i < uie_state.textAreas.length; i ++) { var ta = uie_state.textAreas[i]; %>',
'',
'<%= ta.tagName %>.<%= className(ta.class_name) %> {',
'<%= ta.style %>',
'}',
'',
'<% } %>',
'',
'/* * * * * * * * * * *',
' Lines',
'* * * * * * * * * * */',
'',
'<% for (var i = 0; i < uie_state.lines.length; i ++) { var l = uie_state.lines[i]; %>',
'',
'<%= l.tagName %>.<%= className(l.class_name) %> {',
'<%= l.style %>',
'}',
'',
'<% } %>',
'',
'/* * * * * * * * * * *',
' Dropdowns',
'* * * * * * * * * * */',
'',
'<% for (var i = 0; i < uie_state.dropdowns.length; i ++) { var d = uie_state.dropdowns[i]; %>',
'',
'<%= d.tagName %>.<%= className(d.class_name) %> {',
'<%= d.style %>',
'}',
'',
'<% } %>',
'',
'/* * * * * * * * * * *',
' Boxes',
'* * * * * * * * * * */',
'',
'<% for (var i = 0; i < uie_state.boxes.length; i ++) { var b = uie_state.boxes[i]; %>',
'',
'<%= b.tagName %>.<%= className(b.class_name) %> {',
'<%= b.style %>',
'}',
'',
'<% } %>',
'',
'/* * * * * * * * * * *',
' Forms',
'* * * * * * * * * * */',
'',
'<% for (var i = 0; i < uie_state.forms.length; i ++) { var b = uie_state.forms[i]; %>',
'',
'<%= b.tagName %>.<%= className(b.class_name) %> {',
'<%= b.style %>',
'}',
'',
'<% } %>',
'',
'/* * * * * * * * * * *',
' Lists',
'* * * * * * * * * * */',
'',
'<% for (var i = 0; i < uie_state.lists.length; i ++) { var b = uie_state.lists[i]; %>',
'',
'<%= b.tagName %>.<%= className(b.class_name) %> {',
'<%= b.style %>',
'}',
'',
'<% } %>'].join('\n');
